before_script:
  - which java
  - which javac
  - java -version
  - javac -version

build:
  cache:
    paths:
      - .gradle
      - build/classes
      - build/resources
      - build/sources
      - build/tmp
  script:
    - export GRADLE_BUILD_SIGNED=true
    - ./gradlew build
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 month
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
