modLoader = "javafml"
loaderVersion = "[1,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "aether_ii"
version = "${file.jarVersion}"
displayName = "The Aether II"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/aether-ii"
logoFile = "aether_ii.png"
credits = "The Aether Team, former Aether Team Collaborators for their prior work on The Aether II Mod, GitHub contributors for their additional help, and C4 for Curios API, the source code of which can be found at https://github.com/TheIllusiveC4/Curios"
authors = "bconlon, Hugo Payn, Jaryt, Oscar Payn"
description = '''
    Work in progress...
    '''

[[dependencies.aether_ii]]
    modId="neoforge"
    type = "required"
    versionRange="[20.4.200,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_ii]]
    modId="minecraft"
    type = "required"
    versionRange="[1.20.4]"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config="aether_ii.mixins.json"