modLoader = "javafml"
loaderVersion = "[43,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "aether_ii"
version = "${file.jarVersion}"
displayName = "The Aether II"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/aether-ii"
logoFile = "aether_ii.png"
credits = "The Aether Team AKA 'Gilded Games', former Aether Team Collaborators for their prior work on The Aether II Mod, GitHub contributors for their additional help, and C4 for Curios API, the source code of which can be found at https://github.com/TheIllusiveC4/Curios"
authors = "bconlon, Hugo Payn, Jaryt, Oscar Payn"
description = '''
    Work in progress...
    '''

[[dependencies.aether_ii]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.38,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_ii]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.19.2-5.1.1.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_ii]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2]"
    ordering = "NONE"
    side = "BOTH"