# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0.282

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: git clone -b master https://github.com/Gilded-Games/OrbisLib lib/orbis-lib
      - run: ./gradle -c lib/orbis-lib/build.gradle build
      - store_artifacts:
              path: ~/repo/lib/orbis-lib/build/libs/orbis-lib-1.12.2-0.2.0-SNAPSHOT-universal.jar

      - run: chmod +x gradlew

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/repo/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew test
      - run: ./gradlew build
      - store_artifacts:
              path: ~/repo/build/libs